  jobs:
    include:
      - stage: create image
        os: linux
        dist: focal
        language: generic
        vm:
          create:
            name: testimg_c3
  
      - stage: use custom image
        vm:
          use: testimg_c3
        script:
          - echo "Running job with custom image"
