dist: focal
language: c
script: echo "testtest"
jobs:
  include:
  - vm:
      create:
        name: 'testimg_v111'
  - vm:
      create:
        name: 'testimg_v211'
  - vm:
      create:
        name: 'testimg_v311'
  - vm:
      create:
        name: 'testimg_v411'
  - vm:
      create:
        name: 'testimg_v511'
